[workspace]
authors = ["Lev Kozlov <kozlov.l.a10@gmail.com>"]
name = "pixi_panda_ros2"
version = "0.1.0"
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["scripts/set_ros_env.sh", "install/setup.bash"]

[dependencies]
python = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"

[target.linux.dependencies]
libgl-devel = "*"

[environments]
jazzy = { features = ["jazzy", "dev"] }
lerobot = { features = ["lerobot"], no-default-feature = true }

# ROS2 Jazzy Feature
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.4.0,<4"
poco = "<1.13.0"
ros-jazzy-desktop = "*"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-xacro = ">=2.0.13,<3"
ros-jazzy-generate-parameter-library = "*"
rosdep = "*"
ros-jazzy-topic-tools = ">=1.3.3,<2"
ros-jazzy-topic-tools-interfaces = ">=1.3.3,<2"
pyzmq = ">=27.0.0,<28"

[feature.jazzy.tasks]
update-submodules = "git submodule update --init --recursive"
clone-crisp = "test -d src/crisp_controllers || git clone https://github.com/utiasDSL/crisp_controllers.git src/crisp_controllers"
build = "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev --symlink-install"
setup = { depends-on = ["update-submodules", "clone-crisp", "build"] }
franka = "ros2 launch franka_bringup franka.launch.py"
send = "python src/so100_to_ros/send_to_ros.py"

[feature.jazzy.pypi-dependencies]
crisp-python = ">=3.6.0, <4"

# Development tools
[feature.dev.pypi-dependencies]
ruff = "*"
pytest = "*"
crisp-python = ">=3.0.0,<4"

[feature.lerobot.tasks]
teleoperate = "python src/so100_to_ros/teleoperate.py"

[feature.lerobot.dependencies]
evdev = ">=1.9.2,<2"
pyzmq = ">=27.0.0,<28"

[feature.lerobot.pypi-dependencies]
scipy = ">=1.18.0, <2"
lerobot = { version = ">=0.5.1, <0.6", extras = ["kinematics", "feetech"] }
cmeel-urdfdom = "==4.0.1"
cmeel-tinyxml2 = "==10.0.0"

[feature.lerobot.activation]
scripts = []

[pypi-dependencies]
filelock = ">=3.20.3, <4"
